### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by eyalcha** [maorcc/citymind_water_meter#28] opened 2022-08-07 17:50 UTC
Is the change in Arad website(read your meter pro) has influence on this integration?

https://rym-pro.com/#/

**Comment by elad-bar** [comment] 2022-08-07 17:54
Working for me

**Comment by eyalcha** [comment] 2022-08-07 18:17
@elad-bar yes, I have tried it and it also works for me, but maybe it is because the old website is still up (https://cp.city-mind.com/Login.aspx). I think by the end of this month it will be shutdown.

**Comment by nitaybz** [comment] 2022-10-11 13:19
I can't use the integration because I'm a new user that can only login to their newer website, I don't have account on the old website and I believe this integration works on the old website...

@eyalcha is your previous integration support the new website?

**Comment by nitaybz** [comment] 2022-10-11 13:51
I just investigated on their website and it seems pretty much straight forward... you have one simple call for login:
https://api.city-mind.com/consumer/login
with body:
{"email":"user@gmail.com","pw":"password","deviceId":"anything_can_be_here"}

this retrieves a token that you can use  in any other call later on (doesn't seem to have expiration date)

example call for daily consumption:
https://api-ctm.city-mind.com/consumption/daily/lastbillingCycle/%20%20%20%201625/2022-09-10/2022-10-11

you need to add the token from the login call and add is as a "x-access-token" header.

hope it will help to speed things up :)
Thanks

**Comment by elad-bar** [comment] 2022-10-11 13:55
@nitaybz thanks for the details, I will try working during the weekend, 
I didn't manage to register to their platform, hope that by the weekend it will work for me,
saw that they have changed the code to be a real web API so hopefully we will be able to integrate the component much better than what we have right now

**Comment by GalKar83** [comment] 2022-10-15 07:12
@elad-bar It seems as if you register through the new website (rym-pro.com) and you don't have a user for the old website the username & password isn't recognized.
Is there any chance you make the required adjustments for the new website?

**Comment by elad-bar** [comment] 2022-10-15 07:51
thanks, as I wrote before I have mapped all the API (and also reintegrate the API), it's only because I managed to login,
the only thing left to do is:
- Make sure the entities created correctly
- Support multiple meters
- Support actions (change alerts)

hope that by end of the day i'll have new release working with the new API

thanks

**Comment by elad-bar** [comment] 2022-10-15 14:29
integration almost ready, need to check and fix the update alerts (already read them and have select, but update is not working yet)

![image](https://user-images.githubusercontent.com/3207137/195991863-5c4fafe0-ec94-48e6-adef-338960ce164f.png)

**Comment by elad-bar** [comment] 2022-10-15 15:34
integration is in PR:
https://github.com/maorcc/citymind_water_meter/pull/29

**Comment by GalKar83** [comment] 2022-10-17 04:51
@elad-bar  Thanks for updating the integration, I can confirm it works for me now.
However I tried to use the recommended Lovelace Mini Graph Card and it seems as if I don't get any information from the suggested URL ('https://cp.city-mind.com/Default.aspx') even after adding the water meter serial number.
Is there any chance there is a new URL that will work for me?

**Comment by elad-bar** [comment] 2022-10-17 05:20
Not sure i understand the question, site you have mentioned is the deprecated one, in v2 we are not using it anymore

**Comment by GalKar83** [comment] 2022-10-17 05:29
In the documentation you mentioned the recommended option to add Mini graph card and you added the script needed for it to work.
However, the URL weblink still pointing to the old website and therefore I'm not getting the graphs.
I'm guessing that by changing the weblink it can work and wonder what's the proper URL address.

**Comment by GalKar83** [comment] 2022-10-17 21:44
@elad-bar 
Can you please share the right URL in the meantime?

**Comment by elad-bar** [comment] 2022-10-18 04:21
Available in the first post

**Comment by GalKar83** [comment] 2022-10-18 04:31
If you mean:
https://rym-pro.com/#/

Then it's not working for the Mini Graph Card.

**Comment by elad-bar** [comment] 2022-10-18 05:13
Do you mean:
```yaml
- type: weblink
    url: 'https://cp.city-mind.com/Default.aspx
```

**Comment by GalKar83** [comment] 2022-10-18 06:01
Yes
![Screenshot 2022-10-18 090019](https://user-images.githubusercontent.com/48556131/196348018-497b4e1c-4933-4847-b3a7-358c6cdc68cb.png)

**Comment by elad-bar** [comment] 2022-10-18 06:06
# v2.0.2 released

**Updated documentation and better failed login error handling**

- Add error handling for failed login
- Updated documentation
- Fixed login error message on installation / configuration UI

## Breaking Change - v1 to v2

Version 1.x of integration created to support [cp.city-mind.com](https://cp.city-mind.com) portal,
this portal is end of life set to 31/12/2022.

Version 2.x of integration is to support the new portal of [Read Your Meter Pro](https://rym-pro.com/#/),
Please note that if credentials for 2 portals are different and requires registration,
Please follow the prerequisites section below to make sure the integration will work for you.

If your city is not supported by new Read Your Meter Pro portal, you can keep using v1.x of integration up until the previous portal is EOL.

**Comment by elad-bar** [comment] 2022-10-18 06:07
> Yes ![Screenshot 2022-10-18 090019](https://user-images.githubusercontent.com/48556131/196348018-497b4e1c-4933-4847-b3a7-358c6cdc68cb.png)

if you meant for the errors in card, that's not related to the URL, that's because the name of the entities changed, you need to find them and update accordingly, the card was not created by us, it's just an example how to use it.

As for the URL, just replace it and it will redirect to the new portal.

**Comment by GalKar83** [comment] 2022-10-18 06:18
Indeed the (Read)ing (in the entity name) made the difference.
Thanks, working as expected:-)

**Comment by elad-bar** [comment] 2022-10-18 06:41
> Indeed the (Read)ing (in the entity name) made the difference. Thanks, working as expected:-)

great, thanks for the update :)

**Comment by elad-bar** [comment] 2022-10-18 06:42
can we close this issue?
will create later this evening a thread in home-assistant forum, we can also have a discord channel if you would like, just let me know what you prefer

**Comment by GalKar83** [comment] 2022-10-18 07:13
Yes, you can close the issue.
Many thanks for you support and effort.

**Comment by elad-bar** [comment] 2022-10-18 07:14
thanks!

**Closed by elad-bar** 2022-10-18 07:14 UTC

**Comment by nitaybz** [comment] 2022-10-18 07:16
Thank you very much :)
